echo -e "[34m"
echo -e "        _                           ____"
echo -e "  _ __ (_)_ __  _ __   ___ _ __    / ->/|"
echo -e " | '_ \\| | '_ \\| '_ \\ / _ \\ '__|  /<-_/ |"
echo -e " | | | | | |_) | |_) |  __/ |     |   | /"
echo -e " |_| |_|_| .__/| .__/ \\___|_|     |___|/"
echo -e "         |_|   |_|"
echo -e ""
echo -e "    The Network Infrastructure Parser"
echo -e "[0m"

#echo "Building debug nipper..."
#gcc -g -Wall -o nipper nipper.c

echo "Building nipper..."
gcc -o nipper nipper.c

echo "Installing nipper..."
cp nipper /usr/bin/
cp nipper.conf /etc/
cp man/nipper.1 /usr/share/man/man1/
cp man/nipper.conf.5 /usr/share/man/man5/
