# Install script for directory: /home/dbryan/libnipper-0.12.6

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

FILE(INSTALL DESTINATION "/usr/lib" TYPE SHARED_LIBRARY COMPONENTS "Unspecified" FILES "/home/dbryan/libnipper-0.12.6/libnipper.so")
FILE(INSTALL DESTINATION "/etc" TYPE FILE COMPONENTS "Unspecified" FILES "/home/dbryan/libnipper-0.12.6/nipper.conf")
FILE(INSTALL DESTINATION "/usr/include/libnipper" TYPE FILE COMPONENTS "Unspecified" FILES "/home/dbryan/libnipper-0.12.6/libnipper.h")
FILE(INSTALL DESTINATION "/usr/include/libnipper" TYPE FILE COMPONENTS "Unspecified" FILES "/home/dbryan/libnipper-0.12.6/config.h")
FILE(INSTALL DESTINATION "/usr/share/man/man5" TYPE FILE COMPONENTS "Unspecified" FILES "/home/dbryan/libnipper-0.12.6/man/nipper.conf.5")
IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)
FILE(WRITE "/home/dbryan/libnipper-0.12.6/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "/home/dbryan/libnipper-0.12.6/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
